version: '3'
services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    network_mode: bridge
    restart: always
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - '9100:9100'