# https://storage.googleapis.com/kubernetes-release
# https://storage.googleapis.com/kubernetes-release/release/v1.19.13/kubernetes-server-linux-amd64.tar.gz
# https://storage.googleapis.com/kubernetes-release/release/v1.20.10/kubernetes-server-linux-amd64.tar.gz
# https://storage.googleapis.com/kubernetes-release/release/v1.21.2/kubernetes-server-linux-amd64.tar.gz
# https://storage.googleapis.com/kubernetes-release/release/v1.21.4/kubernetes-server-linux-amd64.tar.gz
# https://storage.googleapis.com/kubernetes-release/release/v1.22.1/kubernetes-server-linux-amd64.tar.gz
- name: Get k8s-server binary files
  ansible.builtin.unarchive:
    src: http://192.168.1.6:8888/kubernetes-server-v1.21.4-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: get executable-files in remote /tmp/kubernetes/server/bin
  find:
    paths: "/tmp/kubernetes/server/bin"
    recurse: false
    file_type: file
    patterns: '*'
    excludes: '*.docker_tag,*.tar,kubelet,kube-proxy,kube-proxy'
  register: executable_files

- debug: msg="{{executable_files}}"

- name: copy executable-files to /usr/local/bin
  become: true
  copy:
    remote_src: yes
    src: "{{item.path}}"
    dest: "/usr/local/bin"
    mode: '755'
  loop: "{{ executable_files.files }}"

- name: ensure directory /etc/kubernetes/ssl exists
  become: true
  file:
    path: /etc/kubernetes/ssl
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Copy kube-apiserver-csr.json to /etc/kubernetes/ssl
  become: true
  template:
    src: "templates/{{ item }}"
    dest: /etc/kubernetes/ssl
  with_items:
    - ca-config.json
    - kube-apiserver-csr.json
    - admin-csr.json
    - kube-controller-manager-csr.json
    - kube-scheduler-csr.json
  when: 
    - etcd_name == "etcd-01"

- name: Copy ca-key.pem,ca-config.json to /etc/kubernetes/ssl
  become: true
  copy:
    src: "/etc/etcd/ssl/{{ item }}"
    dest: "/etc/kubernetes/ssl"
    remote_src: yes
  with_items:
    - ca.pem
    - ca-key.pem
  when: 
    - etcd_name == "etcd-01"

- name: generate kube-apiserver.pem, kube-apiserver-key.pem kube-apiserver.csr
  become: true
  shell: "cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-apiserver-csr.json | cfssljson -bare kube-apiserver"
  args:
    chdir: /etc/kubernetes/ssl
    creates: /etc/kubernetes/ssl/kube-apiserver.pem
  when: 
    - etcd_name == "etcd-01"

- name: get token_random
  shell: "head -c 16 /dev/urandom | od -An -t x | tr -d ' '"
  args:
    creates: /etc/kubernetes/token.csv
  register: token_random
  when: 
    - etcd_name == "etcd-01"

- debug: msg="{{token_random}}"
  when: 
    - etcd_name == "etcd-01"

- name: /etc/kubernetes/ssl/token.csv
  become: true
  ansible.builtin.copy:
    dest: "/etc/kubernetes/token.csv"
    force: false
    content: |
      {{ token_random.stdout_lines[0] }},kubelet-bootstrap,10001,"system:kubelet-bootstrap"
  when: 
    - etcd_name == "etcd-01"

- name: fetch etcd-01 ssl to local tmp
  become: true
  fetch:
    src: "/etc/kubernetes/ssl/{{ item }}"
    dest: /tmp
  with_items: ["kube-apiserver.csr", "ca-key.pem", "ca.pem", "kube-apiserver-key.pem", "kube-apiserver.pem"]
  when: 
    - etcd_name == "etcd-01"

- name: copy etcd-01 ssl to etcd-02 and ectd-03
  become: true
  copy:
    src: "/tmp/k8s-master01/etc/kubernetes/ssl/{{ item }}"
    dest: "/etc/kubernetes/ssl/{{ item }}"
  with_items: ["kube-apiserver.csr", "ca-key.pem", "ca.pem", "kube-apiserver-key.pem", "kube-apiserver.pem"]
  when: 
    - etcd_name == "etcd-02" or etcd_name == "etcd-03"

- name: fetch etcd-01 token.csv to local tmp
  become: true
  fetch:
    src: "/etc/kubernetes/token.csv"
    dest: /tmp
  when: 
    - etcd_name == "etcd-01"

- name: copy etcd-01 token.csv to etcd-02 and ectd-03
  become: true
  copy:
    src: "/tmp/k8s-master01/etc/kubernetes/token.csv"
    dest: "/etc/kubernetes/token.csv"
  when: 
    - etcd_name == "etcd-02" or etcd_name == "etcd-03"

- name: Copy kube-apiserver.conf config to /etc/kubernetes
  become: true
  template:
    src: "templates/kube-apiserver.conf"
    dest: /etc/kubernetes/

- name: Copy kube-apiserver.service to /usr/lib/systemd/system/
  become: true
  template:
    src: templates/kube-apiserver.service
    dest: /usr/lib/systemd/system/

- name: Enable service kube-apiserver and ensure it is not masked
  become: true
  ansible.builtin.systemd:
    name: kube-apiserver
    enabled: yes
    masked: no

- name: Just force systemd to reread configs
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Make sure kube-apiserver service is running
  become: true
  ansible.builtin.systemd:
    name: kube-apiserver
    state: started

- name: generate admin.pem, admin-key.pem etcd.csr
  become: true
  shell: "cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes admin-csr.json | cfssljson -bare admin"
  args:
    chdir: /etc/kubernetes/ssl
    creates: /etc/kubernetes/ssl/admin.pem
  when: 
    - etcd_name == "etcd-01"

- name: fetch etcd-01 admin.* to local tmp
  become: true
  fetch:
    src: "/etc/kubernetes/ssl/{{ item }}"
    dest: /tmp
  with_items: ["admin.csr", "admin-key.pem", "admin.pem"]
  when: 
    - etcd_name == "etcd-01"

- name: copy etcd-01 admin.* to etcd-02 and ectd-03
  become: true
  copy:
    src: "/tmp/k8s-master01/etc/kubernetes/ssl/{{ item }}"
    dest: "/etc/kubernetes/ssl/{{ item }}"
  with_items: ["admin.csr", "admin-key.pem", "admin.pem"]
  when: 
    - etcd_name == "etcd-02" or etcd_name == "etcd-03"

- name: generate /etc/kubernetes/ssl/kube.config
  become: true
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=ca.pem --embed-certs=true --server=https://{{ node_host }}:6443 --kubeconfig=kube.config
    kubectl config set-credentials admin --client-certificate=admin.pem --client-key=admin-key.pem --embed-certs=true --kubeconfig=kube.config
    kubectl config set-context kubernetes --cluster=kubernetes --user=admin --kubeconfig=kube.config
    kubectl config use-context kubernetes --kubeconfig=kube.config
  args:
    chdir: /etc/kubernetes/ssl
    creates: /etc/kubernetes/ssl/kube.config

- name: Ensure /home/deploy/.kube directory
  become: true
  ansible.builtin.file:
    path: /home/deploy/.kube
    state: directory
    owner: deploy
    group: deploy

- name: copy kube.config to ~/.kube/config
  become: true
  copy:
    remote_src: yes
    src: "/etc/kubernetes/ssl/kube.config"
    dest: "/home/deploy/.kube/config"
    owner: deploy
    group: deploy
    mode: u+rw,g-rwx,o-rwx

# - name: test kubectl command
#   shell: |
#     kubectl cluster-info
#     kubectl get componentstatuses
#     kubectl get all --all-namespaces
#   register: stdout

# - debug: msg="{{ stdout.stdout_lines }}"

- name: generate kube-controller-manager.pem, kube-controller-manager-key.pem kube-controller-manager.csr
  become: true
  shell: |
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-controller-manager-csr.json | cfssljson -bare kube-controller-manager
  args:
    chdir: /etc/kubernetes/ssl
    creates: /etc/kubernetes/ssl/kube-controller-manager.pem
  when: 
    - etcd_name == "etcd-01"

- name: generate kube-scheduler.pem, kube-scheduler-key.pem kube-scheduler.csr
  become: true
  shell: |
    cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-scheduler-csr.json | cfssljson -bare kube-scheduler
  args:
    chdir: /etc/kubernetes/ssl
    creates: /etc/kubernetes/ssl/kube-scheduler.pem
  when: 
    - etcd_name == "etcd-01"

- name: fetch etcd-01 kube-controller-manager.*,kube-scheduler.* to local tmp
  become: true
  fetch:
    src: "/etc/kubernetes/ssl/{{ item }}"
    dest: /tmp
  with_items: ["kube-controller-manager.csr", "kube-controller-manager-key.pem", "kube-controller-manager.pem", "kube-scheduler.csr", "kube-scheduler-key.pem", "kube-scheduler.pem"]
  when: 
    - etcd_name == "etcd-01"

- name: copy etcd-01 kube-controller-manager.*,kube-scheduler.* to etcd-02 and ectd-03
  become: true
  copy:
    src: "/tmp/k8s-master01/etc/kubernetes/ssl/{{ item }}"
    dest: "/etc/kubernetes/ssl/{{ item }}"
  with_items: ["kube-controller-manager.csr", "kube-controller-manager-key.pem", "kube-controller-manager.pem", "kube-scheduler.csr", "kube-scheduler-key.pem", "kube-scheduler.pem"]
  when: 
    - etcd_name == "etcd-02" or etcd_name == "etcd-03"

- name: generate /etc/kubernetes/kube-controller-manager.kubeconfig
  become: true
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=/etc/kubernetes/ssl/ca.pem --embed-certs=true --server=https://{{ node_host }}:6443 --kubeconfig=kube-controller-manager.kubeconfig
    kubectl config set-credentials system:kube-controller-manager --client-certificate=/etc/kubernetes/ssl/kube-controller-manager.pem --client-key=/etc/kubernetes/ssl/kube-controller-manager-key.pem --embed-certs=true --kubeconfig=kube-controller-manager.kubeconfig
    kubectl config set-context system:kube-controller-manager --cluster=kubernetes --user=system:kube-controller-manager --kubeconfig=kube-controller-manager.kubeconfig
    kubectl config use-context system:kube-controller-manager --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: /etc/kubernetes
    creates: /etc/kubernetes/kube-controller-manager.kubeconfig

- name: generate /etc/kubernetes/kube-scheduler.kubeconfig
  become: true
  shell: |
    kubectl config set-cluster kubernetes --certificate-authority=/etc/kubernetes/ssl/ca.pem --embed-certs=true --server=https://{{ node_host }}:6443 --kubeconfig=kube-scheduler.kubeconfig
    kubectl config set-credentials system:kube-scheduler --client-certificate=/etc/kubernetes/ssl/kube-scheduler.pem --client-key=/etc/kubernetes/ssl/kube-scheduler-key.pem --embed-certs=true --kubeconfig=kube-scheduler.kubeconfig
    kubectl config set-context system:kube-scheduler --cluster=kubernetes --user=system:kube-scheduler --kubeconfig=kube-scheduler.kubeconfig
    kubectl config use-context system:kube-scheduler --kubeconfig=kube-scheduler.kubeconfig
  args:
    chdir: /etc/kubernetes
    creates: /etc/kubernetes/kube-scheduler.kubeconfig

- name: Copy kube-controller-manager.conf and kube-scheduler.conf to /etc/kubernetes
  become: true
  template:
    src: "templates/{{ item }}"
    dest: /etc/kubernetes/
  with_items: ["kube-controller-manager.conf", "kube-scheduler.conf"]

- name: Copy kube-controller-manager.service and kube-scheduler.service to /usr/lib/systemd/system/
  become: true
  template:
    src: "templates/{{ item }}"
    dest: /usr/lib/systemd/system/
  with_items: ["kube-controller-manager.service", "kube-scheduler.service"]

- name: Enable kube-controller-manager.service and kube-scheduler.service and ensure it is not masked
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items: ["kube-controller-manager.service", "kube-scheduler.service"]

- name: Just force systemd to reread configs
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Make sure kube-controller-manager.service and kube-scheduler.service is running
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
  with_items: ["kube-controller-manager.service", "kube-scheduler.service"]
