---

- name: install etcd
  become: true
  become_method: sudo
  apt:
    name: etcd-server
    update_cache: yes
    state: present

- name: copy config to /etc/default/etcd
  template:
    src: templates/etcd.j2
    dest: /etc/default/etcd

- name: remove directories
  become: true
  become_method: sudo
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ etcd_data_dir }}"
    - "{{ etcd_wal_dir }}"

- name: prepare data dir
  become: true
  become_method: sudo
  file:
    path: "{{ item }}"
    state: directory
    owner: etcd
    group: etcd
    mode: '0700'
  with_items:
    - "{{ etcd_data_dir }}"
    - "{{ etcd_wal_dir }}"

- name: restart etcd
  systemd:
    state: restarted
    name: etcd