# - debug: msg="{{ ansible_pkg_mgr }}"
# - debug: msg="{{ ansible_distribution }}"
# - debug: msg="{{ ansible_distribution_major_version }}"
# - debug: msg="{{ ansible_hostname }}"
# - debug: msg="{{ ansible_interfaces }}"

- name: configure /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ item.ip }}'
    line: "{{ item.ip }}\t{{ item.hostname }}"
    state: present
  loop: "{{ etc_hosts }}"

- name: load lsb_release -sc
  shell: lsb_release -sc
  register: lsb_release_sc_data

- name: load lsb_release -si
  shell: lsb_release -si
  register: lsb_release_si_data

- name: set facts
  set_fact:
    lsb_release_sc: "{{ lsb_release_sc_data.stdout_lines[0] }}"
    lsb_release_si: "{{ lsb_release_si_data.stdout_lines[0] }}"

- name: Copy ubuntu_apt_sources.list to /etc/apt/
  become: true
  shell: cp sources.list sources.list_bak
  args:
    chdir: /etc/apt/
    creates: /etc/apt/sources.list_bak
  when:
    - lsb_release_si == 'Ubuntu' or lsb_release_si == 'Debian'

- name: Copy ubuntu_apt_sources.list to /etc/apt/
  become: true
  template:
    src: templates/ubuntu_apt_sources.list
    dest: /etc/apt/sources.list
  when:
    - lsb_release_si == 'Ubuntu'
    - mirrors_url is defined
  notify: reload-apt

- name: Copy debian_apt_sources.list to /etc/apt/
  become: true
  template:
    src: templates/debian_apt_sources.list
    dest: /etc/apt/sources.list
  when:
    - lsb_release_si == 'Debian' 
    - mirrors_url is defined
  notify: reload-apt

- name: run once setup
  become: true
  shell: |
    swapoff -a
    timedatectl set-timezone "{{ timezone }}"
    timedatectl set-ntp true

# sed -i -r "/(.*)swap(.*)swap(.*)/d" /etc/fstab
# sysctl -w vm.swappiness=0
- name: disable swap
  become: true
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    state: absent
  
# ulimit -SHn 65535
- name: config unlimit
  become: true
  lineinfile:
    path: /etc/security/limits.conf
    regexp: '{{ item.regexp }}'
    line: "{{ item.line }}"
    state: present
  loop: "{{ ulimit_conf }}"

- name: Install coreutils procps net-tools sysstat etc
  become: true
  become_method: sudo
  apt:
    name: [ 'coreutils', 'procps', 'libseccomp2', 'net-tools', 'sysstat', 'rsync', 'bash-completion' ]
    update_cache: yes
    state: present
  when: lsb_release_si == 'Ubuntu' or lsb_release_si == 'Debian'

- name: Enable IPVS
  become: true
  become_method: sudo
  apt:
    name: [ 'ipvsadm', 'ipset', 'conntrack' ]
    update_cache: yes
    state: present
  when: lsb_release_si == 'Ubuntu' or lsb_release_si == 'Debian'

- name: Setup /etc/modules-load.d/k8s.conf
  become: true
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      module=(
        overlay
        ip_vs
        ip_vs_rr
        ip_vs_wrr
        ip_vs_lc
        ip_vs_wlc
        ip_vs_sh
        ip_vs_dh
        br_netfilter
        nf_conntrack
      )

- name: modprobe br_netfilter
  become: true
  shell: modprobe br_netfilter

- name: Enable systemd-modules-load started
  become: true
  ansible.builtin.systemd:
    name: systemd-modules-load.service
    enabled: yes
    masked: no

- name: Start systemd-modules-load started
  become: true
  ansible.builtin.systemd:
    name: systemd-modules-load.service
    daemon_reload: yes
    state: started

# 修改linux的内核参数，添加网桥过滤和地址转发功能
- name: Setup sysctl for k8s.conf
  become: true
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.ipv4.tcp_keepalive_time = 600
      net.ipv4.tcp_keepalive_intvl = 30
      net.ipv4.tcp_keepalive_probes = 10

- name: sysctl k8s.conf
  become: true
  sysctl: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/k8s.conf
    sysctl_set: yes
  with_items:
    - name: net.bridge.bridge-nf-call-iptables
      value: 1
    - name: net.bridge.bridge-nf-call-ip6tables
      value: 1
    - name: net.ipv4.ip_forward
      value: 1
    - name: net.ipv4.tcp_keepalive_time
      value: 600
    - name: net.ipv4.tcp_keepalive_intvl
      value: 30
    - name: net.ipv4.tcp_keepalive_probes
      value: 10
