---
# https://docs.docker.com/engine/install/binaries/
- name: Get docker binary files
  unarchive:
    src: "{{ binaries_fs }}/binaries/x86_64/docker/docker-20.10.8.tgz"
    dest: /tmp
    remote_src: yes

- name: get docker_binaries in remote /tmp/docker
  ansible.builtin.find:
    paths: "/tmp/docker"
    recurse: false
    file_type: file
    patterns: '*'
  register: docker_binaries

- name: copy docker_binaries to /usr/local/bin
  become: true
  copy:
    remote_src: yes
    src: "{{ item.path }}"
    dest: "/usr/local/bin"
    mode: ugo+x
  loop: "{{ docker_binaries.files }}"

- name: Ensure group "docker" exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the user 'deploy' to group 'docker'
  become: true
  become_method: sudo
  ansible.builtin.user:
    name: deploy
    groups: docker
    append: yes

- name: Ensure /etc/docker directory exists
  become: true
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root

# https://kubernetes.io/zh/docs/setup/production-environment/container-runtimes/#docker
- name: Change Cgroup Driver
  become: true
  template:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json

- name: Copy docker services to /usr/lib/systemd/system/
  become: true
  template:
    src: "templates/{{ item }}"
    dest: /usr/lib/systemd/system/
  with_items:
    - containerd.service
    - docker.socket
    - docker.service
  
- name: Enable docker services and ensure it is not masked
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items:
    - containerd.service
    - docker.socket
    - docker.service

- name: Make sure docker services is running
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - docker.socket
    - containerd.service
    - docker.service

- name: Reload docker service
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
    state: reloaded
    name: docker.service


#- name: docker run hello-world
#  become: true
#  become_method: sudo
#  command: docker run --rm hello-world
