---
# https://docs.docker.com/engine/install/binaries/
- name: Get docker binary files
  become: true
  unarchive:
    src:  {{ binaries_fs }}/binaries/x86_64/docker/docker-20.10.8.tgz
    dest: /usr/local/bin
    remote_src: yes
    mode: ugo+x

- name: Ensure group "docker" exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the user 'deploy' to group 'docker'
  become: true
  become_method: sudo
  ansible.builtin.user:
    name: deploy
    groups: docker
    append: yes

# https://kubernetes.io/zh/docs/setup/production-environment/container-runtimes/#docker
- name: Change Cgroup Driver
  become: true
  template:
    src: templates/daemon.json
    dest: /etc/docker/daemon.json

- name: Copy docker services to /usr/lib/systemd/system/
  become: true
  template:
    src: "templates/{{ item }}"
    dest: /usr/lib/systemd/system/
  with_items:
    - containerd.service
    - docker.socket
    - docker.service
  
- name: Enable docker services and ensure it is not masked
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items:
    - containerd.service
    - docker.socket
    - docker.service

- name: Just force systemd to reread configs
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Make sure docker services is running
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
  with_items:
    - containerd.service
    - docker.socket
    - docker.service

#- name: docker run hello-world
#  become: true
#  become_method: sudo
#  command: docker run --rm hello-world
