apiVersion: v1
kind: Service
metadata:
  name: redis-standalone
  labels:
    app: redis-standalone
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30379
  selector:
    app: redis-standalone