- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
  
- name: enable-docker-service
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no
  with_items:
    - containerd.service
    - docker.socket
    - docker.service

- name: restart-docker-service
  become: true
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ item }}"
  with_items:
    - docker.socket
    - containerd.service
    - docker.service