# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'hyperv'


Vagrant.configure("2") do |config|
    (1..3).each do |i|
        config.vm.define "k8s-node01#{i}" do |c|
            c.vm.box = "generic/ubuntu2204"

            c.vm.network "public_network", bridge: "global-bridge", ip: "192.168.1.11#{i}"

            c.vm.hostname = "k8s-node01#{i}"

            c.vm.provider :hyperv do |v|
                v.cpus = 2
                v.memory = 2048
                v.maxmemory = 8192
                v.vmname = "k8s-node01#{i}"
                v.mac = "00:15:5D:01:52:0#{i}"
            end

            c.vm.provision "shell", inline: <<-SHELL
                export DEBIAN_FRONTEND=noninteractive

                localectl set-locale LANG=zh_CN.UTF-8
                dpkg-reconfigure --frontend noninteractive locales
                timedatectl set-timezone Asia/Shanghai

                apt update 2>/dev/null
                apt -y install net-tools socat 2>/dev/null

                useradd -m -s /bin/bash -u 1001 james
                usermod -aG sudo james
                usermod -aG adm james
                usermod -a -G users james
                usermod -a -G staff james
                echo 'james ALL = (ALL) NOPASSWD: ALL' | tee /etc/sudoers.d/james  > /dev/null
                mkdir -p /home/james/.ssh
                echo 'ssh-ed25519 AAAAC... zizhizhan@gmail.com' | tee -a /home/james/.ssh/authorized_keys
                chown -R james:james /home/james/.ssh

                echo "initialize k8s-node01#{i} done"
            SHELL
      end
    end
end

