- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
  
- name: enable-etcd-service
  become: true
  ansible.builtin.systemd:
    name: etcd
    enabled: yes
    masked: no

- name: restart-etcd-service
  become: true
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: etcd