- name: Print ansible debug information 
  vars: 
    ansible_msg: |
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
        Ansible Pkg Mgr: {{ ansible_pkg_mgr }}
        Ansible OS Family: {{ ansible_os_family }}
        Ansible Hostname: {{ ansible_hostname }}
        Ansible Nodename: {{ ansible_nodename }}
        Inventory Hostname: {{ inventory_hostname }}
        Group Names: {{ group_names }}
        Groups: {{ groups }}
        Role: {{ role }}
  debug: 
    msg: "{{ ansible_msg.split('\n') }}"
  tags: debug_info


# - debug: msg="{{ hostvars }}"
