apiVersion: v1
kind: ConfigMap
metadata:
  name: pma-config
  namespace: geek-apps
data:
  PMA_HOSTS: 'mysql-primary,mysql-secondary,192.168.1.6'
  PMA_VERBOSES: 'mysql-primary,mysql-secondary,synology-db'
  PMA_PORT: '3306'
  PMA_ABSOLUTE_URI: https://pma.zizhizhan.com
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: synology-phpmyadmin
  namespace: geek-apps
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: synology-phpmyadmin
        image: phpmyadmin
        imagePullPolicy: IfNotPresent    
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/www/html/config.inc.php"
          subPath: config.inc.php
          name: pma-config-inc-vol
          readOnly: true
        envFrom:
        - secretRef:
            name: pma-user-pass
        - configMapRef: 
            name: pma-config
      volumes:
      - name: pma-config-inc-vol
        configMap:
          name: pma-config-inc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pma-service
  namespace: geek-apps
  labels:
    app: phpmyadmin
spec:
  clusterIP: None
  ports:
  - targetPort: 80
    port: 80
    name: httpport
  selector:
    app: phpmyadmin

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  namespace: geek-apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - pma.zizhizhan.com
    secretName: star.zizhizhan.com-tls
  rules:
  - host: pma.zizhizhan.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-pma-service
            port:
              number: 80