k8s_master_host: 192.168.1.61

service_cluster_ip_range: 192.168.1.128/25
cluster_cidr: 10.244.0.0/16

core_dns_ip: 192.168.1.130

resolv_conf: /run/systemd/resolve/resolv.conf
static_pod_path: /etc/kubernetes/manifests
pod_infra_container_image: registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.4.1

kube_proxy_mode: "ipvs"     # kube-proxy mode, like: iptables ipvs, default ipvs