mirrors_url: https://mirrors.tuna.tsinghua.edu.cn
timezone: Asia/Shanghai

etc_hosts:
  - ip: 192.168.1.61
    hostname: k8s-master01
  - ip: 192.168.1.62
    hostname: k8s-master02
  - ip: 192.168.1.63
    hostname: k8s-master03
  - ip: 192.168.1.101
    hostname: k8s-node001
  - ip: 192.168.1.102
    hostname: k8s-node002
  - ip: 192.168.1.106
    hostname: k8s-node006
  - ip: 192.168.1.107
    hostname: k8s-node007
  - ip: 192.168.1.108
    hostname: k8s-node008
  - ip: 192.168.1.111
    hostname: k8s-node011
  - ip: 192.168.1.112
    hostname: k8s-node012
  - ip: 192.168.1.115
    hostname: k8s-node015
  - ip: 192.168.1.116
    hostname: k8s-node016
  - ip: 192.168.1.117
    hostname: k8s-node017
  - ip: 192.168.1.121
    hostname: k8s-node021
  - ip: 192.168.1.122
    hostname: k8s-node022
  - ip: 192.168.1.123
    hostname: k8s-node023

ulimit_conf:
  - regexp: /^\*(.*)soft(.*)nofile(.*)/
    line: "* soft nofile 655360"
  - regexp: /^\*(.*)soft(.*)nofile(.*)/
    line: "* hard nofile 131072"
  - regexp: /^\*(.*)soft(.*)nproc(.*)/
    line: "* soft nproc 655350"
  - regexp: /^\*(.*)hard(.*)nproc(.*)/
    line: "* hard nproc 655350"
  - regexp: /^\*(.*)soft(.*)memlock(.*)/
    line: "* soft memlock unlimited"
  - regexp: /^\*(.*)hard(.*)memlock(.*)/
    line: "* hard memlock unlimited"
