- name: Print ansible debug information
  vars:
    ansible_msg: |
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
        Ansible Pkg Mgr: {{ ansible_pkg_mgr }}
        Ansible OS Family: {{ ansible_os_family }}
        Ansible Hostname: {{ ansible_hostname }}
        Ansible Nodename: {{ ansible_nodename }}
        Inventory Hostname: {{ inventory_hostname }}
        Group Names: {{ group_names }}
        Groups: {{ groups }}
  debug:
    msg: "{{ ansible_msg.split('\n') }}"
  tags: debug_info

- name: Show ansible varialbes
  debug:
    msg: |
      inventory_hostname: {{ inventory_hostname }}
      inventory_hostname_short: {{ inventory_hostname_short }}
      inventory_dir: {{ inventory_dir }}"
      inventory_file: {{ inventory_file }}
      ansible_play_batch: {{ ansible_play_batch }}
      ansible_play_hosts: {{ ansible_play_hosts }}
      ansible_playbook_python: {{ ansible_playbook_python }}
      ansible_check_mode: {{ ansible_check_mode }}
      playbook_dir: {{ playbook_dir }}

# - name: Display HostVars
#   debug: msg="{{ hostvars }}"
