apiVersion: v1
kind: Endpoints
metadata:
  name: synology-dsm
  namespace: geek-apps
subsets:
  - addresses:
      - ip: 192.168.1.6
    ports:
      - port: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: synology-dsm
  namespace: geek-apps
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dsm-ingress
  namespace: geek-apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - dsm.zizhizhan.com
    secretName: star.zizhizhan.com-tls
  rules:
  - host: dsm.zizhizhan.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: synology-dsm
            port:
              number: 5000
