apiVersion: v1
kind: Endpoints
metadata:
  name: xiaomi-router
  namespace: geek-apps
subsets:
  - addresses:
      - ip: 192.168.1.1
    ports:
      - port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: xiaomi-router
  namespace: geek-apps
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xiaomi-router-ingress
  namespace: geek-apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
      - mi.zizhizhan.com
    secretName: star.zizhizhan.com-tls
  rules:
  - host: mi.zizhizhan.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: xiaomi-router
            port:
              number: 80
