- name: Add the user 'deploy' with primary group of 'sudo'
  become: true
  become_method: sudo
  ansible.builtin.user:
    name: deploy
    comment: Deploy For User
    groups: sudo,users
    shell: /bin/bash

- name: sudo without password
  become: true
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/deploy"
    content: |
      deploy ALL = (ALL) NOPASSWD: ALL

- name: Create backup folder
  become: true
  ansible.builtin.file:
    path: /home/deploy/.ssh
    state: directory
    owner: deploy
    group: deploy

- name: ssh without password
  become: true
  ansible.builtin.copy:
    src: ~/.ssh/id_rsa.pub
    dest: /home/deploy/.ssh/authorized_keys
    owner: deploy
    group: deploy
    mode: u+rw,g-rwx,o-rwx

- name: copy local key_pair(public) to remote
  become: true
  ansible.builtin.copy:
    src: ~/.ssh/id_rsa.pub
    dest: /home/deploy/.ssh/id_rsa.pub
    owner: deploy
    group: deploy
    mode: u+rw,g-wx,o-wx

- name: copy local key_pair(private) to remote
  become: true
  ansible.builtin.copy:
    src: ~/.ssh/id_rsa
    dest: /home/deploy/.ssh/id_rsa
    owner: deploy
    group: deploy
    mode: u+rw,g-rwx,o-rwx