users:
  - name: ubuntu
    groups: [adm, admin, sudo, staff, users]
    sudo: ["ALL = (ALL) NOPASSWD: ALL"]
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICKlyozoHszgLnnamHPPPyfivgCuv39aItv9eGkgdE8F zizhizhan@gmail.com
fqdn: k8s-node02.local
write_files:
  - path: /etc/cloud/templates/hosts.debian.tmpl
    content: |
      192.168.64.21    k8s-node01
      192.168.64.22    k8s-node02
      192.168.64.23    k8s-node03
    append: true