apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration

bindAddress: 0.0.0.0
clientConnection:
  kubeconfig: /etc/kubernetes/kube-proxy.kubeconfig
clusterCIDR: {{ cluster_cidr }}

healthzBindAddress: 0.0.0.0:10256
metricsBindAddress: 127.0.0.1:10249
hostnameOverride: "{{ inventory_hostname }}"
mode: {{ kube_proxy_mode }}