apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration

staticPodPath: {{ static_pod_path }}
syncFrequency: 1m
fileCheckFrequency: 20s
httpCheckFrequency: 20s

address: 0.0.0.0
port: 10250

# rotateCertificates: false
rotateCertificates: true

authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/ssl/ca.pem

authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s

healthzPort: 10248
healthzBindAddress: 127.0.0.1

clusterDomain: cluster.local
clusterDNS:
  - {{ core_dns_ip }}

streamingConnectionIdleTimeout: 4h
nodeStatusUpdateFrequency: 10s
nodeStatusReportFrequency: 5m
imageMinimumGCAge: 2m
volumeStatsAggPeriod: 1m

# cgroupDriver: cgroupfs
cgroupDriver: systemd

cpuManagerReconcilePeriod: 10s
runtimeRequestTimeout: 2m

{% if lsb_distributor == 'Ubuntu' %}
resolvConf: /run/systemd/resolve/resolv.conf
{% else %}
resolvConf: /etc/resolv.conf
{% endif %}

evictionPressureTransitionPeriod: 5m

logging: 
  format: text

shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s