- name: load docker daemon.json
  become: true
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: install snapd
  become: true
  become_method: sudo
  apt:
    name: snapd
    update_cache: yes
    state: present
  notify:
    - show-snap-version

- name: Install "MicroK8s" with options
  become: true
  snap:
    name: microk8s
    classic: yes
    channel: 1.22/stable

- name: sudo usermod -a -G microk8s deploy
  become: true
  user:
    name: deploy
    group: microk8s

- name: load pause images
  command: |
    microk8s.ctr images pull registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1
    microk8s.ctr images tag registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.1 k8s.gcr.io/pause:3.1
    
- name: microk8s.enable dns registry
  command: microk8s.enable dns registry

- name: copy nginx-microk8s.yml
  template:
    src: "{{ item }}" 
    dest: /tmp/
  with_items:
    - nginx-microk8s.yml
    - default.conf

- name: deploy nginx-microk8s.yml
  shell: |
    microk8s.kubectl create configmap nginx-server-config --from-file=/tmp/default.conf
    microk8s.kubectl apply -f /tmp/nginx-microk8s.yml