---

- hosts: all
  tasks:
  - name: Update and upgrade apt packages
    become: true
    become_method: sudo
    apt:
      update_cache: yes
      upgrade: 'yes'
      state: latest
      autoremove: 'yes'
      autoclean: 'yes'
      cache_valid_time: 3600