- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: enable-kubelet-proxy-service
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    masked: false
  with_items:
    - kubelet.service
    - kube-proxy.service

- name: restart-kubelet-proxy-service
  become: true
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{ item }}"
  with_items:
    - kubelet.service
    - kube-proxy.service
